### ISSUE TITLE
Support of TCP transport 

### ISSUE THREAD

**Issue by f1xpl** [f1xpl/aasdk#1]
Support TCP transport in order to use AndroidAuto wireless.

**Comment by duxet** [comment]
From what i saw, the Wi-Fi connection is initiated by connecting through Bluetooth first, is that right?

**Comment by borconi** [comment]
Two ways to accomplish this. One unofficial you start the headunit server from AA on the phone, you creat a WiFi hotspot on the phone connect the unit to it the you can connect to the phones IP at port 5277, this works have been using it for 2 years now.

Other way, the official one, on the setup when you connect the phone with usb the first time the headunit also includes an SSID to the car setup, after that the raspberry creates the hotspot with the same SSID. Now when the phone connects to this WiFi it will try to initialize the connection, this will be the official way but I haven't worked this one out so research and extra reverse engineering still needs to be done.

**Comment by f1xpl** [comment]
Changes merged to development branch.

**Comment by parkerlreed** [comment]
Does this still need the feature/wireless branch of openauto? (If it's even in a working state yet)

**Comment by f1xpl** [comment]
@parkerlreed feature branch will be removed soon.
