### ISSUE TITLE
Can't build with different resolution

### ISSUE THREAD

**Issue by DaanRademaker** [f1xpl/aasdk#12]
First of all thank you the work on this open-source project, quite groundbreaking to have android auto open-sourced. 

I have a question regarding building  aasdk on hardware with a different resolution (a nexus 9 running ubuntu with resolution of  1536 x 2048 pixels, 4:3 ratio (~281 ppi density)

When issuing the make command I get an enum error regarding the video resolutions. I think it comes from the proc below. Is there a way to add more supported resolutions or the interface of android auto cannot simply scale with this different aspect ratio? 

My apologies if the submission of this issue is done in a "noob" way this is my first git issue :) 

```+/*
+*  This file is part of aasdk library project.
+*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
+*
+*  aasdk is free software: you can redistribute it and/or modify
+*  it under the terms of the GNU General Public License as published by
+*  the Free Software Foundation; either version 3 of the License, or
+*  (at your option) any later version.
+
+*  aasdk is distributed in the hope that it will be useful,
+*  but WITHOUT ANY WARRANTY; without even the implied warranty of
+*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+*  GNU General Public License for more details.
+*
+*  You should have received a copy of the GNU General Public License
+*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
+*/
+
+syntax="proto3";
+
+package f1x.aasdk.proto.enums;
+
+message VideoResolution
+{
+    enum Enum
+    {
+        NONE = 0;
+        _480p = 1;
+        _720p = 2;
+       _1080p = 3;
+    }
+}

**Comment by f1xpl** [comment]
Hello,
please provide mentioned error message - it will be easier to investigate the issue. It occurs during aasdk build or OpenAuto build?

Android Auto supports projection only in 3 resolutions - 480p, 720p and 1080p. 720p and 1080p are available only when you enable them in Android Auto developer settings.

Basically it is just a resolution of the video stream. It depends on your video player how it will be rendered on the screen. If you want to keep aspect ratio then I suppose video will be cropped horizontally (in case of screen with 4:3 aspect ratio). Most of the video players have option to ignore aspect ratio and fill whole screen. This is how it works in OpenAuto - aspect ratio will be ignored to fill whole surface of your screen. Also you can adjust Screen DPI in OpenAuto settings to adjust appearance of AndroidAuto. 

Latest changes available on development contain also ability to adjust video margins (in case of overscan).

**Comment by parkerlreed** [comment]
@f1xpl In this case they mean the nexus 9 IS the computer/Pi in this case. So the computer running OpenAuto has a 4:3 screen which end up looking like

![screenshot from 2018-03-15 13-50-28](https://user-images.githubusercontent.com/841440/37481359-e8f9d7e0-2857-11e8-9286-6e30e6ae7d7b.png)

@DaanRademaker As far as I'm aware, the 480/720/1080 are the only options you have and are hardcoded probably on the Android Auto application side of things. The video margins @f1xpl mentioned may help if they are able to correct the aspect but you'll end up with bars on the top and bottom.
