### ISSUE TITLE
Wireless Connection Text Box Default

### ISSUE THREAD

**Issue by ctatos** [f1xpl/aasdk#15]
Hi, first off, great work. It's a fun project!

I was wondering if we could put a default IP address whenever tapping on the Wireless Connection button. For some reason, the recent connections is always blank. Unless we have a USB keyboard connected to the raspberry pi, there is no way to type in the text box.

Whenever I activate the phone's hotspot, it always defaults to a local IP of 192.0.0.4. It would be interesting to hardcode this into the text field for wireless...

Thanks,
Charles

**Comment by f1xpl** [comment]
Feature is still under development.

**Comment by ctatos** [comment]
No problem, I'll wait. In the meantime, I hacked something up via pynput. It works pretty well!
http://pythonhosted.org/pynput/keyboard.html

**Comment by f1xpl** [comment]
@ctatos Please test lastes changes on OpenAuto's development branch.

**Comment by parkerlreed** [comment]
@f1xpl I assume this still needs the Play Services to be updated on the phone side? Not seeing a headunit server option as of yet.

**Comment by parkerlreed** [comment]
Aha I see it's in the little menu and not actually in the developer settings submenu. It works! :D
