### ISSUE TITLE
Raspbian Fetching error

### ISSUE THREAD

**Issue by MrThinkage** [f1xpl/aasdk#19]
I'm new to raspberry pi and command line tasks so help would be greatly appreciated. When attempting to install the necessary applications for aasdk I got this error sequence:

Err:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf icu-devtools armhf 57.1-6+deb9u1
  404  Not Found [IP: 93.93.128.193 80]
Err:2 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libicu-dev armhf 57.1-6+deb9u1
  404  Not Found [IP: 93.93.128.193 80]
Err:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libssl-dev armhf 1.1.0f-3+deb9u1
  404  Not Found [IP: 93.93.128.193 80]
Err:4 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libssl-doc all 1.1.0f-3+deb9u1
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/i/icu/icu-devtools_57.1-6+deb9u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/i/icu/libicu-dev_57.1-6+deb9u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-dev_1.1.0f-3+deb9u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl-doc_1.1.0f-3+deb9u1_all.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by jeremiah** [comment]
It looks like the URL you're trying to pull from for raspbian is not online for some reason. When I click on the link in your error message I'm getting a 404 error too. However the base URL appears available: http://mirrordirector.raspbian.org/raspbian/

**Comment by parkerlreed** [comment]
`sudo apt-get update && sudo apt-get upgrade`

**Comment by f1xpl** [comment]
You have the hint in error message:

> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Execution of this command will fix the problem.
