### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by htruong** [f1xpl/aasdk#21]
I was just studying your code and saw the typo. This should be angle :)

https://github.com/f1xpl/aasdk/blob/07c1e83f9f81aaee464da5fb96c1ad0f797722fe/aasdk_proto/SteeringWheelData.proto#L25

**Comment by f1xpl** [comment]
Please create a pull request with the correction.

**Comment by htruong** [comment]
Created a pull request! Sorry for the delay.
