### ISSUE TITLE
Building on regular Linux/x86_64

### ISSUE THREAD

**Issue by parkerlreed** [f1xpl/aasdk#4]
Attempting to build and install on Arch x86_64.

Got it built with cmake/make, but the Makefile doesn't offer an `install` option. How do I install this for it to be picked up by the `openauto` build?

**Comment by parkerlreed** [comment]
Copying the include/ contents to my local /usr/include let the `openauto` build continue but ended up with a ton of undefined references when linking `autoapp`

**Comment by parkerlreed** [comment]
Ended up customizing the build instructions here and got it running! https://github.com/htruong/crankshaft/wiki/Building-the-binary-blobs

![screenshot_20180226_173049](https://user-images.githubusercontent.com/841440/36699645-4b727f02-1b1b-11e8-840f-a2a1d699b610.png)

**Comment by f1xpl** [comment]
At the OpenAuto wiki you have official build instruction.

**Comment by parkerlreed** [comment]
Ahh thanks. That seems to only cover aasdk while the crankshaft wiki also got me what I needed for openauto. Maybe a mashup of the two would suffice. 

Either way, thanks for this wonderful project. Already did some testing with my existing portable computer https://www.youtube.com/watch?v=POybXgob7nk

**Comment by parkerlreed** [comment]
I'm an idiot. Missed the openauto GitHub wiki. :| 

Thanks again!
