### ISSUE TITLE
Connecting Bluethooth

### ISSUE THREAD

**Issue by misterbaldi** [f1xpl/aasdk#6]
Hello together,

first at all, such a nice project 👍 
i am not sure how to connect a speaker and a microphone to the raspberry.
I tried to connect a bluetooth headset to the raspi an set the soundcard to it,
but it was not working.
Is there a tutorial or a how to?
In future i want to connect the wires of my car hifi to the raspi

reagards,
Thomas

**Comment by f1xpl** [comment]
Hello,
I think the official Raspberry PI forums will be more helpful if you need to deal with custom hardware or configuration. aasdk related to the higher level of the Raspbian system and it is not related directly to the hardware.
